services:
  db:
    image: postgres:latest
    container_name: db
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    env_file:
      - .env.development
    ports:
      - "6379:6379"
    command:
      - valkey-server
      - --requirepass
      - ${VALKEY_PASSWORD}
      - --save
      - "60"
      - "1"
      - --appendonly
      - yes
    volumes:
      - valkey-data:/data
volumes:
  db-data:
  valkey-data: